---
title: "Regression"
subtitle: ""
author: ""
date: "2024-04-28"
draft: false
---

```{r}
library(tidyverse) 
library(ggplot2)
library(dplyr) 
library(MASS)
ds <- read_rds("dataset/load_and_clean_data.rds") 
```

```{r}
conditions=factor(ds$condition)
age=as.factor(ds$AGE_GROUP)
sex=factor(ds$PERP_SEX)
race=factor(ds$PERP_RACE)
boro=factor(ds$ARREST_BORO)
temp=ds$temp
windspeed=ds$windspeed
crime=data.frame(conditions,age,sex,race,boro,temp,windspeed)
str(crime)
```

```{r}
df_y <- ds %>%
  filter(OFNS_DESC == "ASSAULT 3 & RELATED OFFENSES") %>%
  group_by(temp,conditions,AGE_GROUP, PERP_SEX, PERP_RACE, ARREST_BORO) %>%
  summarise(y = n(), .groups = 'drop')


mod1 <- glm(y ~ temp+conditions+AGE_GROUP + PERP_SEX + PERP_RACE + ARREST_BORO , 
           data = df_y, 
           family = poisson())


```


```{r}
hist(temp, breaks = 50, probability = TRUE, main = "Histogram of temp ", xlab = "Volume", col = "lightblue")
hist(windspeed, breaks = 50, probability = TRUE, main = "Histogram of windspeed", xlab = "Volume", col = "lightblue")

ggplot(ds, aes(x = age)) +
  geom_bar() +  # This creates a bar chart
  labs(title = "Distribution of Age Groups", x = "Age Group", y = "Frequency") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

ggplot(ds, aes(x = race)) +
  geom_bar() +  # This creates a bar chart
  labs(title = "Distribution of RACE", x = "RACE", y = "Frequency") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 


ggplot(ds, aes(x = race)) +
  geom_bar() +  # This creates a bar chart
  labs(title = "Distribution of BORO", x = "BORO", y = "Frequency") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

df_y$temp_range <- cut(df_y$temp,
                      breaks = c(-Inf, 10, 20, 30, 40, Inf),
                      labels = c("<10", "11-20", "21-30", "31-40", ">40"),
                      include.lowest = TRUE)

ggplot(df_y, aes(x = y, fill = temp_range)) +
  geom_density(alpha = 0.4) +
  labs(title = "Density of 'y' for Temperature Ranges",
       x = "'y' value",
       fill = "Temperature Range")

ggplot(df_y,aes(x = y, color = conditions,fill=conditions))+geom_density(alpha=0.4)



```







```{r}
df_y1 <- ds %>%
  group_by(temp,windspeed,conditions,AGE_GROUP, PERP_SEX, PERP_RACE, ARREST_BORO) %>%
  summarise(y = n(), .groups = 'drop')


mod <- glm(y ~ temp+conditions+AGE_GROUP + PERP_SEX + PERP_RACE + ARREST_BORO , 
           data = df_y, 
           family = poisson())
# Summary of the model
summary(mod)
```


```{r}
par(mfrow=c(2,2))
plot(mod)
```

```{r}
with(mod,cbind(res.deviance = deviance, df = df.residual, p=pchisq(deviance, df.residual,lower.tail=FALSE)))
```





```{r}

df_y1 <- ds %>%
  filter(OFNS_DESC == "ASSAULT 3 & RELATED OFFENSES") %>%
  group_by(temp,conditions,AGE_GROUP, PERP_SEX, PERP_RACE, ARREST_BORO) %>%
  summarise(y = n(), .groups = 'drop')

mod_temp <- glm(y ~ temp, 
           data = df_y1, 
           family = poisson())
par(mfrow=c(2,2))
summary(mod_temp)
plot(mod_temp)
qqnorm(df_y$temp)
qqline(df_y$temp, col = "red")
```




```{r}
mod_step = step(mod,direction="both")
summary(mod_step)
```


```{r}
condition_glm= glm(y~conditions,data=df_y,family=poisson)
summary(condition_glm)
```









