---
title: "Regression"
subtitle: ""
author: "TEAM 14"
date: "2024-04-28"
draft: false
---

```{r}
library(tidyverse) 
library(ggplot2)
library(dplyr) 
ds <- read_rds("dataset/load_and_clean_data.rds") 
```

```{r}
conditions=factor(ds$condition)
age=factor(ds$AGE_GROUP)
sex=factor(ds$PERP_SEX)
race=factor(ds$PERP_RACE)
boro=factor(ds$ARREST_BORO)
temp=ds$temp
windspeed=ds$windspeed
crime=data.frame(conditions,age,sex,race,boro,temp,windspeed)
str(crime)


df_y <- ds %>%
  filter(OFNS_DESC == "ASSAULT 3 & RELATED OFFENSES") %>%
  group_by(cloudcover,temp,conditions,AGE_GROUP, PERP_SEX, PERP_RACE, ARREST_BORO) %>%
  summarise(y = n(), .groups = 'drop')


mod <- glm(y ~ temp+conditions+AGE_GROUP + PERP_SEX + PERP_RACE + ARREST_BORO , 
           data = df_y, 
           family = poisson())

mod1 <- lm(y ~ temp+conditions+AGE_GROUP + PERP_SEX + PERP_RACE + ARREST_BORO , 
           data = df_y, 
           family = poisson())

# Summary of the model
summary(mod)
summary(mod1)

```



```{r}
# Calculate the minimum temperature
min_temp <- min(ds$temp, na.rm = TRUE)

# Calculate the maximum temperature
max_temp <- max(ds$temp, na.rm = TRUE)

# Output the results
cat("Minimum temperature:", min_temp, "\n")
cat("Maximum temperature:", max_temp, "\n")


```

```{r}
with(mod,cbind(res.deviance = deviance, df = df.residual, p=pchisq(deviance, df.residual,lower.tail=FALSE)))
```

```{r}
mod_step = step(mod,direction="both")
```
```{r}
mod_step=glm(y ~ AGE_GROUP + PERP_SEX + PERP_RACE + ARREST_BORO, data = df_y, family = poisson)
summary(mod_step)
```

```{r}
ggplot(df_y,aes(x = y, color = conditions,fill=conditions))+geom_density(alpha=0.4)
```

```{r}
condition_glm= glm(y~conditions,data=df_y,family=poisson)
summary(condition_glm)
```
```{r}
temp_glm= glm(y~ cloudcover+temp,data=df_y,family=poisson)
summary(temp_glm)
```

```{r}
df_y$temp_range <- cut(df_y$temp,
                      breaks = c(-Inf, 10, 20, 30, 40, Inf),
                      labels = c("<10", "11-20", "21-30", "31-40", ">40"),
                      include.lowest = TRUE)
df_y$windspeed_range <- cut(df_y$windspeed,
                            breaks = c(-Inf, 10, 20, 30, 40, Inf),
                            labels = c("<10", "11-20", "21-30", "31-40", ">40"),
                            include.lowest = TRUE)
ggplot(df_y, aes(x = y, fill = temp_range)) +
  geom_density(alpha = 0.4) +
  labs(title = "Density of 'y' for Temperature Ranges",
       x = "'y' value",
       fill = "Temperature Range")
ggplot(df_y, aes(x = y, fill = windspeed_range)) +
  geom_density(alpha = 0.4) +
  labs(title = "Density of 'y' for Wind Speed Ranges",
       x = "'y' value",
       fill = "Wind Speed Range")

```
```{r}
temp_glm= glm(y~temp_range+windspeed_range,data=df_y,family=poisson)
summary(temp_glm)
```

```{r}
install.packages("glmnet")
library(glmnet)
# Convert factors to dummy variables
df_y_matrix <- model.matrix(y ~ . - 1, data = df_y)

# Create a vector for the response variable
y_vector <- df_y$y

# Set up the ridge regression with glmnet (lambda could be a sequence of values for regularization strength)
ridge_mod <- glmnet(df_y_matrix, y_vector, family = "poisson", alpha = 0)

# Plot the ridge model
plot(ridge_mod)

```

