---
title: "6th Blog Post"
subtitle: ""
author: "TEAM 14"
date: "2024-04-22"
draft: false
---

We imported the Google Maps api to create heat maps to analyze where the highest amount of crime is in NYC, and also broke down the distribution of the top three crime categories in NYC.
```{r}
library(dplyr)
library(tidyverse) 
library(ggplot2)
library(dplyr)
library(kableExtra)
library(ggcorrplot)
library(ggmap)
library(leaflet)
library(patchwork)
ds <- read_rds("dataset/load_and_clean_data.rds")
```

```{r include =F}
ds |> dplyr::filter(Latitude > 30, Longitude < -40) -> ds
bbox <- make_bbox(lon = Longitude, lat = Latitude, data = ds, f = 0.1)
a <- get_map(bbox)
ggmap(a)

ds <- ds |> mutate(ARREST_DATE =mdy(ARREST_DATE))
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
#2022 ASSAULT 3

ds |> dplyr::filter(OFNS_DESC == 'ASSAULT 3 & RELATED OFFENSES',
                    ARREST_DATE >= as.Date("2022-01-01") & ARREST_DATE <= as.Date("2022-12-31"))|>
  group_by(Longitude, Latitude) |>
  count(name = 'n') |> 
  mutate(G = cut(n, breaks = c(0, 1, 2, 3, 1523),
                 labels = c('1', '2', '3', '>3'), 
                 include.lowest = T)) -> df_22as

plot_2022as<- ggmap(a) +
  geom_point(data = df_22as, aes(x = Longitude, y = Latitude, color = G),
             alpha = 0.5, size = 0.5) +
  labs(x = 'Longitude', y = 'Latitude', color = '', title = 'ASSAULT 3 2022') +
  scale_color_manual(values = c('seagreen', 'blue', 'orange', 'tomato')) +
  theme(legend.position = 'top')
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
# 2023 ASSAULT 3

ds |> dplyr::filter(OFNS_DESC == 'ASSAULT 3 & RELATED OFFENSES',
                    ARREST_DATE >= as.Date("2023-01-01") & ARREST_DATE <=  as.Date("2023-12-31"))|>
  group_by(Longitude, Latitude) |>
  count(name = 'n') |> 
  mutate(G = cut(n, breaks = c(0, 1, 2, 3, 1523),
                 labels = c('1', '2', '3', '>3'), 
                 include.lowest = T)) -> df_23as

plot_2023as <- ggmap(a) +
  geom_point(data = df_23as, aes(x = Longitude, y = Latitude, color = G),
             alpha = 0.5, size = 0.5) +
  labs(x = 'Longitude', y = 'Latitude', color = '', title = 'ASSAULT 3 2023') +
  scale_color_manual(values = c('seagreen', 'blue', 'orange', 'tomato')) +
  theme(legend.position = 'top')

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
combined_plot <- plot_2022as + plot_2023as
combined_plot
```
```{r}
# 2023 ASSAULT 3 S

ds |> dplyr::filter(OFNS_DESC == 'ASSAULT 3 & RELATED OFFENSES',
                    ARREST_DATE >= as.Date("2023-03-01") & ARREST_DATE <=  as.Date("2023-5-31"))|>
  group_by(Longitude, Latitude) |>
  count(name = 'n') |> 
  mutate(G = cut(n, breaks = c(0, 1, 2, 3, 1523),
                 labels = c('1', '2', '3', '>3'), 
                 include.lowest = T)) -> df_23ass

plot_2023ass <- ggmap(a) +
  geom_point(data = df_23ass, aes(x = Longitude, y = Latitude, color = G),
             alpha = 0.5, size = 0.5) +
  labs(x = 'Longitude', y = 'Latitude', color = '', title = 'ASSAULT 3 2023 S') +
  scale_color_manual(values = c('seagreen', 'blue', 'orange', 'tomato')) +
  theme(legend.position = 'top')


#ASS 3 2023 F

ds |> dplyr::filter(OFNS_DESC == 'ASSAULT 3 & RELATED OFFENSES',
                    ARREST_DATE >= as.Date("2022-9-01") & ARREST_DATE <=  as.Date("2022-10-30"))|>
  group_by(Longitude, Latitude) |>
  count(name = 'n') |> 
  mutate(G = cut(n, breaks = c(0, 1, 2, 3, 1523),
                 labels = c('1', '2', '3', '>3'), 
                 include.lowest = T)) -> df_23asf
plot_2023asf<- ggmap(a) +
  geom_point(data = df_23asf, aes(x = Longitude, y = Latitude, color = G),
             alpha = 0.5, size = 0.5) +
  labs(x = 'Longitude', y = 'Latitude', color = '', title = 'ASSAULT 3 2022f') +
  scale_color_manual(values = c('seagreen', 'blue', 'orange', 'tomato')) +
  theme(legend.position = 'top')


```

```{r}
combined_plot_season <- plot_2023ass + plot_2023asf
combined_plot_season
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# PETIT LARCENY 2022
ds |> dplyr::filter(OFNS_DESC == 'PETIT LARCENY',
                    ARREST_DATE >= as.Date("2022-01-01") & 
                    ARREST_DATE <=    as.Date("2022-12-31"))|>
  group_by(Longitude, Latitude) |>
  count(name = 'n') |> 
  mutate(G = cut(n, breaks = c(0, 1, 2, 3, 1523),
                 labels = c('1', '2', '3', '>3'), 
                 include.lowest = T)) -> df_res_pt22

plot_2022pt <- ggmap(a) +
  geom_point(data = df_res_pt22, aes(x = Longitude, y = Latitude, color = G),
             alpha = 0.5, size = 0.5) +
  labs(x = 'Longitude', y = 'Latitude', color = '', title = 'PETIT LARCENY 2022') +
  scale_color_manual(values = c('seagreen', 'blue', 'orange', 'tomato')) +
  theme(legend.position = 'top')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# PETIT LARCENY 2023
ds |> dplyr::filter(OFNS_DESC == 'PETIT LARCENY',
                    ARREST_DATE >= as.Date("2023-01-01") & ARREST_DATE <= as.Date("2023-12-31"))|>
  group_by(Longitude, Latitude) |>
  count(name = 'n') |> 
  mutate(G = cut(n, breaks = c(0, 1, 2, 3, 1523),
                 labels = c('1', '2', '3', '>3'), 
                 include.lowest = T)) -> df_res_pt23

plot_2023pt <- ggmap(a) +
  geom_point(data = df_res_pt23, aes(x = Longitude, y = Latitude, color = G),
             alpha = 0.5, size = 0.5) +
  labs(x = 'Longitude', y = 'Latitude', color = '', title = 'PETIT LARCENY 2023') +
  scale_color_manual(values = c('seagreen', 'blue', 'orange', 'tomato')) +
  theme(legend.position = 'top')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
combined_plot_2 <- plot_2022pt + plot_2023pt
combined_plot_2
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#2022 FA
ds |> dplyr::filter(OFNS_DESC == 'FELONY ASSAULT',
                    ARREST_DATE >= as.Date("2022-01-01") & ARREST_DATE <= as.Date("2022-12-31")) |>
  group_by(Longitude, Latitude) |>
  count(name = 'n') |> 
  mutate(G = cut(n, breaks = c(0, 1, 2, 3, 511),
                 labels = c('1', '2', '3', '>3'), 
                 include.lowest = T)) -> df_fa22

plot_2022fa <- ggmap(a) +
  geom_point(data = df_fa22, aes(x = Longitude, y = Latitude, color = G),
             alpha = 0.5, size = 0.5) +
  labs(x = 'Longitude', y = 'Latitude', color = '', title = 'FELONY ASSAULT 2022') +
  scale_color_manual(values = c('seagreen', 'blue', 'orange', 'tomato')) +
  theme(legend.position = 'top')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#2023 FA
ds |> dplyr::filter(OFNS_DESC == 'FELONY ASSAULT',
                    ARREST_DATE >= as.Date("2023-01-01") & ARREST_DATE <= as.Date("2023-12-31")) |>
  group_by(Longitude, Latitude) |>
  count(name = 'n') |> 
  mutate(G = cut(n, breaks = c(0, 1, 2, 3, 511),
                 labels = c('1', '2', '3', '>3'), 
                 include.lowest = T)) -> df_fa23

plot_2023fa <- ggmap(a) +
  geom_point(data = df_fa23, aes(x = Longitude, y = Latitude, color = G),
             alpha = 0.5, size = 0.5) +
  labs(x = 'Longitude', y = 'Latitude', color = '', title = 'FELONY ASSAULT 2023') +
  scale_color_manual(values = c('seagreen', 'blue', 'orange', 'tomato')) +
  theme(legend.position = 'top')
```

```{r echo=FALSE, message=FALSE, warning= FALSE}
combined_plot_3 <- plot_2022fa + plot_2023fa
combined_plot_3
```

It has some increase 


Thesis: the Crime rate of Assault 3 will increase as temperature rises in the New York City.