---
title: "First Blog Post"
subtitle: "Data Set Selection"
author: "TEAM NA"
date: "2024-03-04"
draft: false
---
Data set 1: US Police Shootings https://www.kaggle.com/datasets/ahsen1330/us-police-shootings

The data set takes out some insights on what factors would affect US police shootings. There are 10 columns and 4896 rows which contain basic information about “name”, “date”, “armed”, “age”, “gender”, “race”, “city”, and so on. The variables like “name” and “states” might be deleted because it seems not to influence the reasons on US shooting cases. We would like to address questions like whether or not factors such as “gender” and “armed” would affect the rate of shooting cases. Also, we could discuss if racism is objectively existing in the US by creating a bar chart to show the amount of US shooting cases based on different races.There are some challenges we need to solve like how to deal with “unknown” in the data set. There is some data with different names that have the same identity and we could change them into one name in order to do the analysis more clearly.


Data set 2: NYPD Arrest Data year 2023 
https://catalog.data.gov/dataset/nypd-arrest-data-year-to-date

The data is from January 1, 2023, to December 1, 2023. It has 226873 rows and 19 different variables.  Which contains the date, the description of the cases, the criminal’s sex, race, and age range. Besides that, it also contains the coordinate of each arrest, and other factors.The NYPD Arrest Data is collected as part of routine police operations, documenting each arrest made by the NYPD. This data is likely collected to monitor crime patterns, assess police performance, and inform public policy and safety measures.

According to the Data, there are several questions we could address or discuss:
The relationship between arrest and demographic factors like sex, race, and age. We also could analyze the trend of the criminal rate through the year. However, we still have some challenges that need to be overcome. The first one is how to combine the coordinates in the data with the arrest cases to illustrate a crime rate region in the map. Also, Arrest data may reflect systemic biases in policing practices, complicating analyses related to race, sex, or age, how we could reduce the bias is the key challenge.


Data set 3 : Heart Disease Mortality Data Among US Adults (35+) by State/Territory and County - Alberto
https://catalog.data.gov/dataset/heart-disease-mortality-data-among-us-adults-35-by-state-territory-and-county

The data set presented provides an in-depth look at heart disease mortality among U.S. adults aged 35 and older, segmented by state, territory, and county levels. Each row corresponds to a unique data entry, likely representing a specific demographic group within a geographic region. The data et contains information on the year of data collection, geographic identifiers, the data source, and specific details about the nature of the data, such as whether it relates to heart disease prevalence or mortality rates. Metrics such as the value, unit, and type of data are included, offering numerical information that could reflect mortality rates per capita or total reported cases.

Additionally, the data set is structured by categories such as gender, race, and ethnicity, allowing for a multifaceted analysis of heart disease impact across different populations. This enables public health officials and researchers to visualize disparities in health outcomes and potentially identify high-risk areas or groups. Footnote symbols and explanations provide context for the data values, highlighting nuances or specific considerations, such as data suppression or estimation methods used. This rich data et is an essential tool for forming targeted health interventions, policy-making, and further studies focused on heart disease within the U.S. adult population.

